DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Segler CASCADE;
DROP TABLE IF EXISTS Trainer CASCADE;
DROP TABLE IF EXISTS Boot CASCADE;
DROP TABLE IF EXISTS Tourenboot CASCADE;
DROP TABLE IF EXISTS Sportboot CASCADE;
DROP TABLE IF EXISTS Mannschaft CASCADE;
DROP TABLE IF EXISTS Regatta CASCADE;
DROP TABLE IF EXISTS Wettfahrt CASCADE;
DROP TABLE IF EXISTS bildet;
DROP TABLE IF EXISTS zugewiesen;
DROP TABLE IF EXISTS nimmt_teil;
DROP TABLE IF EXISTS erzielt;

/* -> CASCADE, um abhaengige Tabellen zu loeschen! */